"use client";

import { useState, useEffect } from "react";
import {
    BarChart3,
    Eye,
    DollarSign,
    Film,
} from "lucide-react";
import { cn } from "@/lib/utils";

interface VideoStats {
    total: number;
    byStatus: Record<string, number>;
    totalSegments: number;
    totalRendered: number;
}

export default function AnalyticsPage() {
    const [period, setPeriod] = useState<"7d" | "30d" | "90d" | "all">("30d");
    const [stats, setStats] = useState<VideoStats>({
        total: 0,
        byStatus: {},
        totalSegments: 0,
        totalRendered: 0,
    });
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        async function fetchStats() {
            try {
                const res = await fetch("/api/videos?limit=1000");
                if (res.ok) {
                    const data = await res.json();
                    const videos = data.videos || [];
                    const now = new Date();
                    let daysBack = 0;
                    if (period === "7d") daysBack = 7;
                    else if (period === "30d") daysBack = 30;
                    else if (period === "90d") daysBack = 90;

                    const filtered = daysBack > 0
                        ? videos.filter((v: any) => {
                            const created = new Date(v.createdAt);
                            return (now.getTime() - created.getTime()) / 86400000 <= daysBack;
                        })
                        : videos;

                    const byStatus: Record<string, number> = {};
                    let totalSegments = 0;
                    let totalRendered = 0;

                    for (const v of filtered) {
                        byStatus[v.status] = (byStatus[v.status] || 0) + 1;
                        totalSegments += v._count?.segments || 0;
                    }

                    // Count rendered shorts
                    for (const v of filtered) {
                        if (v.status === "READY") totalRendered++;
                    }

                    setStats({
                        total: filtered.length,
                        byStatus,
                        totalSegments,
                        totalRendered,
                    });
                }
            } catch (err) {
                console.error("Failed to fetch analytics:", err);
            } finally {
                setLoading(false);
            }
        }

        fetchStats();
    }, [period]);

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-white">Analytics</h1>
                    <p className="text-gray-400 text-sm mt-1">
                        Track performance across all published content
                    </p>
                </div>
                <div className="flex items-center bg-gray-900/50 border border-gray-800 rounded-xl overflow-hidden">
                    {(["7d", "30d", "90d", "all"] as const).map((p) => (
                        <button
                            key={p}
                            onClick={() => setPeriod(p)}
                            className={cn(
                                "px-3 py-2 text-xs font-medium transition-colors",
                                period === p
                                    ? "bg-violet-500/15 text-violet-400"
                                    : "text-gray-400 hover:text-white"
                            )}
                        >
                            {p === "all" ? "All Time" : p}
                        </button>
                    ))}
                </div>
            </div>

            {/* Stats Grid */}
            <div className="grid grid-cols-3 gap-4">
                <StatCard
                    icon={Film}
                    label="Videos Ingested"
                    value={loading ? "..." : stats.total.toString()}
                    detail={`${stats.byStatus?.READY || 0} ready`}
                    color="violet"
                />
                <StatCard
                    icon={Eye}
                    label="AI Segments"
                    value={loading ? "..." : stats.totalSegments.toString()}
                    detail="Generated by AI"
                    color="blue"
                />
                <StatCard
                    icon={DollarSign}
                    label="Completed"
                    value={loading ? "..." : stats.totalRendered.toString()}
                    detail="Ready for publishing"
                    color="emerald"
                />
            </div>

            {/* Status Breakdown */}
            <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-6">
                <h3 className="text-sm font-semibold text-white mb-4">Video Pipeline Status</h3>
                {loading ? (
                    <div className="h-32 flex items-center justify-center text-gray-500 text-sm">
                        Loading...
                    </div>
                ) : stats.total === 0 ? (
                    <div className="h-32 flex items-center justify-center">
                        <div className="text-center">
                            <BarChart3 className="w-8 h-8 text-gray-700 mx-auto mb-2" />
                            <p className="text-sm text-gray-500">
                                No videos ingested yet. Import a video to see analytics.
                            </p>
                        </div>
                    </div>
                ) : (
                    <div className="space-y-3">
                        {Object.entries(stats.byStatus).map(([status, count]) => (
                            <div key={status} className="flex items-center gap-3">
                                <span className="text-xs text-gray-400 w-28 truncate">{status}</span>
                                <div className="flex-1 bg-gray-800 rounded-full h-2 overflow-hidden">
                                    <div
                                        className={cn(
                                            "h-full rounded-full transition-all",
                                            status === "READY" ? "bg-emerald-500" :
                                                status === "FAILED" ? "bg-red-500" :
                                                    status === "PENDING" ? "bg-gray-500" :
                                                        "bg-violet-500"
                                        )}
                                        style={{ width: `${(count / stats.total) * 100}%` }}
                                    />
                                </div>
                                <span className="text-xs text-white font-mono w-8 text-right">{count}</span>
                            </div>
                        ))}
                    </div>
                )}
            </div>

            {/* Per-Channel & Per-Video tables */}
            <div className="grid grid-cols-2 gap-4">
                <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-6">
                    <h3 className="text-sm font-semibold text-white mb-3">Per Channel</h3>
                    <p className="text-xs text-gray-500">
                        Channel-level analytics will appear here once you connect channels and publish content.
                    </p>
                </div>
                <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-6">
                    <h3 className="text-sm font-semibold text-white mb-3">Top Videos</h3>
                    <p className="text-xs text-gray-500">
                        Your best-performing shorts ranked by views and engagement will appear here.
                    </p>
                </div>
            </div>
        </div>
    );
}

function StatCard({
    icon: Icon,
    label,
    value,
    detail,
    color,
}: {
    icon: any;
    label: string;
    value: string;
    detail: string;
    color: string;
}) {
    const colorMap: Record<string, string> = {
        blue: "bg-blue-500/10 border-blue-500/20 text-blue-400",
        violet: "bg-violet-500/10 border-violet-500/20 text-violet-400",
        emerald: "bg-emerald-500/10 border-emerald-500/20 text-emerald-400",
    };

    return (
        <div className="bg-gray-900/50 border border-gray-800 rounded-2xl p-5">
            <div className="flex items-center gap-3 mb-3">
                <div className={cn("w-10 h-10 rounded-xl flex items-center justify-center border", colorMap[color])}>
                    <Icon className="w-5 h-5" />
                </div>
                <span className="text-sm text-gray-400">{label}</span>
            </div>
            <div className="flex items-end justify-between">
                <p className="text-3xl font-bold text-white">{value}</p>
                <span className="text-xs text-gray-500">{detail}</span>
            </div>
        </div>
    );
}
