/**
 * TTS Text Formatter
 *
 * Handles two distinct concerns:
 *
 * 1. CONTENT-LEVEL CUES (stored in narrationText)
 *    These are authorial directives embedded in the text itself:
 *    - Dia: (laughs), (sighs), (clears throat), (singing) etc.
 *      → Dia renders these as actual audio sound effects.
 *    - These SHOULD be generated by the AI and stored in the DB.
 *    - Stripping/reformatting is needed when switching engines.
 *
 * 2. STRUCTURAL MARKUP (applied at synthesis time, NOT stored)
 *    - ElevenLabs: <break time="1s"/> injected from narrator-style.ts
 *    - Edge TTS: handled by MoneyPrinterTurbo automatically
 *    - Gemini: clean plain text (Gemini handles pacing internally)
 *    - These are applied in voice/generate/route.ts just before the API call.
 *
 * Engine-specific authoring guide for the AI system prompt:
 *   - edge_tts  → clean natural text, punctuation-driven pacing
 *   - gemini    → clean natural text, expressive word choice, avoid special markup
 *   - elevenlabs → clean text + optionally "..." for trailing pauses (structural markup auto-added)
 *   - dia       → use parenthetical sound effects: (laughs), (sighs), (clears throat), etc.
 */

export type TtsProvider = "edge_tts" | "gemini" | "elevenlabs" | "dia";

// ─────────────────────────────────────────────────────────────────────────────
// Dia vocal effect cues — these are literal parentheticals Dia renders as audio
// ─────────────────────────────────────────────────────────────────────────────
export const DIA_CUES = [
    "(laughs)", "(chuckles)", "(sighs)", "(gasps)", "(clears throat)",
    "(singing)", "(humming)", "(whistles)", "(mumbles)", "(whispers)",
    "(screams)", "(groans)", "(inhales)", "(exhales)", "(coughs)",
    "(sneezes)", "(snorts)", "(hiccups)", "(yawns)", "(applause)",
    "(claps)", "(sobs)", "(cries)", "(roars)", "(barks)"
] as const;

// Regex that matches any Dia cue
const DIA_CUE_REGEX = /\([a-z][a-z\s]+\)/gi;

// ─────────────────────────────────────────────────────────────────────────────
// ElevenLabs structural markup (these are added at synthesis time, not stored)
// ─────────────────────────────────────────────────────────────────────────────
const ELEVENLABS_BREAK_REGEX = /<break\s+time="[\d.]+s"\s*\/>/gi;
const ELEVENLABS_SPEAK_REGEX = /<\/?speak[^>]*>/gi;
const ELEVENLABS_PROSODY_REGEX = /<\/?prosody[^>]*>/gi;

// ─────────────────────────────────────────────────────────────────────────────
// Strip engine-specific markup from stored text
// Use when switching a character from one TTS engine to another.
// ─────────────────────────────────────────────────────────────────────────────
export function stripTtsMarkup(text: string, fromEngine: TtsProvider): string {
    let result = text;

    if (fromEngine === "elevenlabs") {
        result = result.replace(ELEVENLABS_BREAK_REGEX, "");
        result = result.replace(ELEVENLABS_SPEAK_REGEX, "");
        result = result.replace(ELEVENLABS_PROSODY_REGEX, "");
    }

    if (fromEngine === "dia") {
        result = result.replace(DIA_CUE_REGEX, "");
    }

    // Collapse multiple spaces left behind by removals
    return result.replace(/\s{2,}/g, " ").trim();
}

// ─────────────────────────────────────────────────────────────────────────────
// Reformat text when switching engines
// Strips old engine markup, text stays clean for new engine.
// Dia → other: strip cues (they become noise in other engines)
// Other → Dia: AI must regenerate to add cues — we just return clean text here.
// ─────────────────────────────────────────────────────────────────────────────
export function reformatForEngine(
    text: string,
    fromEngine: TtsProvider,
    toEngine: TtsProvider
): { text: string; needsRegeneration: boolean } {
    const stripped = stripTtsMarkup(text, fromEngine);

    // Going TO Dia: clean text won't have Dia cues — needs AI regeneration
    // to fully benefit from the new engine
    if (toEngine === "dia" && fromEngine !== "dia") {
        return { text: stripped, needsRegeneration: true };
    }

    // Coming FROM Dia: cues are stripped, text is now clean for the new engine
    if (fromEngine === "dia" && toEngine !== "dia") {
        return { text: stripped, needsRegeneration: false };
    }

    // All other transitions (e.g. edge_tts → gemini, gemini → elevenlabs):
    // text is already clean — no cues to add or strip
    return { text: stripped, needsRegeneration: false };
}

// ─────────────────────────────────────────────────────────────────────────────
// Apply synthesis-time structural markup
// Called in voice/generate/route.ts JUST BEFORE the TTS API call.
// The result is NOT stored — only the source text is persisted.
// ─────────────────────────────────────────────────────────────────────────────
export function applyStructuralMarkup(text: string, engine: TtsProvider): string {
    // ElevenLabs gets SSML break tags applied by narrator-style.ts (applyStyleForElevenLabs)
    // — we don't duplicate that here, it's handled in the generate route.

    // Gemini, Edge TTS, Dia: clean text is preferred.
    // For Dia: the stored (laughs) cues ARE the markup — no additional wrapping needed.
    return text;
}

// ─────────────────────────────────────────────────────────────────────────────
// AI prompt appendix per TTS engine
// Injected into the system prompt in summarize/route.ts so the AI writes
// engine-appropriate dialogue with the right content-level cues.
// ─────────────────────────────────────────────────────────────────────────────
export function buildTtsWritingGuide(characterTtsMap: Record<string, TtsProvider>): string {
    const hasEdge = Object.values(characterTtsMap).some(e => e === "edge_tts");
    const hasGemini = Object.values(characterTtsMap).some(e => e === "gemini");
    const hasDia = Object.values(characterTtsMap).some(e => e === "dia");
    const hasElevenLabs = Object.values(characterTtsMap).some(e => e === "elevenlabs");

    const charLines = Object.entries(characterTtsMap)
        .map(([name, engine]) => `  - ${name}: ${ENGINE_LABELS[engine]}`)
        .join("\n");

    const guidelines: string[] = [];

    if (hasEdge || hasGemini) {
        guidelines.push(
            `• Edge TTS / Gemini characters: Write clean, natural dialogue. Use punctuation (commas, ellipses, exclamation marks) to convey pacing and emotion. Do NOT add any special markup tags or parenthetical cues — the TTS engine handles pacing automatically.`
        );
    }

    if (hasElevenLabs) {
        guidelines.push(
            `• ElevenLabs characters: Write clean, expressive dialogue. Use "..." for deliberate trailing pauses. Do NOT write <break> XML tags — those are added automatically at synthesis time. Focus on emotionally rich word choice.`
        );
    }

    if (hasDia) {
        guidelines.push(
            `• Dia TTS characters: You MUST naturally embed Dia vocal effect cues in the dialogue text where they serve the emotion of the scene. These cues are rendered as real audio sound effects by Dia. Use them sparingly and only where they genuinely fit:
  Available cues: (laughs) (chuckles) (sighs) (gasps) (clears throat) (singing) (humming) (whistles) (mumbles) (whispers) (screams) (groans) (inhales) (exhales) (coughs) (sneezes) (snorts) (hiccups) (yawns) (sobs) (cries) (roars)
  Example: "I don't know what happened... (sighs) ...I suppose we try again."
  Example: "That's the funniest thing I've ever seen! (laughs) Come on, let's go!"
  Place cues inline in the "text" field — never in visualPrompt.`
        );
    }

    if (guidelines.length === 0) return "";

    return `
TTS VOICE ENGINE AUTHORING RULES (CRITICAL):
Each character has a specific TTS voice engine. You MUST write their dialogue text to match their engine's requirements:

${charLines}

${guidelines.join("\n\n")}

These rules are engine contracts — breaking them causes audio synthesis errors or poor audio quality.`;
}

const ENGINE_LABELS: Record<TtsProvider, string> = {
    edge_tts: "Edge TTS (MoneyPrinter) — clean natural text",
    gemini: "Gemini 2.5 Flash TTS — clean expressive text",
    elevenlabs: "ElevenLabs — clean text, \"...\" for pauses",
    dia: "Dia TTS (RunPod) — use (laughs)(sighs)(gasps) etc. inline"
};

// ─────────────────────────────────────────────────────────────────────────────
// Quick helper: does a given text look like it has Dia cues?
// ─────────────────────────────────────────────────────────────────────────────
export function hasDiaCues(text: string): boolean {
    return DIA_CUE_REGEX.test(text);
}

// ─────────────────────────────────────────────────────────────────────────────
// Quick helper: extract all Dia cues found in a text (for display/debug)
// ─────────────────────────────────────────────────────────────────────────────
export function extractDiaCues(text: string): string[] {
    return text.match(DIA_CUE_REGEX) || [];
}
